#!/usr/bin/php
<?php
require_once('/opt/git_hooks/github-php-client/client/GitHubClient.php');
require_once('/opt/git_hooks/config.inc');
// the auto gen'ed repos should not get pull requests, this hooks comments, explaining why and closes the pull

$org=SQLite3::escapeString($argv[1]);
$repo_name=SQLite3::escapeString($argv[2]);
$pull_id=SQLite3::escapeString($argv[3]);
$username=SQLite3::escapeString($argv[4]);
$user_id=SQLite3::escapeString($argv[5]);
$url="https://agentcontribs.kaltura.org";
$msg="Thank you for contributing this pull request!\nThe $repo_name is autogenerated from https://github.com/kaltura/server under generator/sources/__LANG__\nPlease create a new pull on the server repo.\n";
$client = new GitHubClient();
//$client->setDebug(true);
$client->setCredentials(GITHUB_USER,GITHUB_PASSWD);
$cla_checked=null;
try{
	$client->orgs->members->responseIfRequesterIsNotAnOrganizationMember($org,$username);
	$client->comments->createComment($org, $repo_name, $pull_id, "Hi @".$username.",\n$msg");
	$client->pulls->update($org, $repo_name, $pull_id, 'closed',null,null);

}catch(exception $e){
	throw $e;
}

